# Generated by Django 5.2.18 on 2026-10-11 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("unidad_medida", models.CharField(max_length=50)),
                ("stock_actual", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0,
                                message="El stock mínimo debe ser un número entero no negativo.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia prima",
                "verbose_name_plural": "Materias primas",
                "db_table": "materia_prima",
            },
        ),
    ]
